# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-21 03:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20171108_0408'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.CharField(default='', max_length=2000),
        ),
    ]
