# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-26 04:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inbox', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='recipients',
            field=models.CharField(choices=[('', 'Select')], default='Select', max_length=20, verbose_name='Recipients'),
        ),
    ]
