# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-29 03:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inbox', '0004_auto_20171128_2213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='message_received_by',
            field=models.CharField(default='anon', max_length=20),
        ),
        migrations.AlterField(
            model_name='message',
            name='message_sent_by',
            field=models.CharField(default='anon', max_length=20),
        ),
    ]
