# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-03 20:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inbox', '0005_auto_20171128_1948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='sent_time',
            field=models.DateField(auto_now_add=True),
        ),
    ]
