# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-15 04:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Riff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('priv_vis', models.BooleanField(default=True)),
                ('riff_key', models.CharField(choices=[(b'', b'Select'), (b'Amaj', b'Amaj'), (b'Bmaj', b'Bmaj'), (b'Cmaj', b'Cmaj'), (b'Dmaj', b'Dmaj'), (b'Emaj', b'Emaj'), (b'Fmaj', b'Fmaj'), (b'Gmaj', b'Gmaj'), (b'Abmaj', b'Abmaj'), (b'Bbmaj', b'Bbmaj'), (b'Dbmaj', b'Dbmaj'), (b'Ebmaj', b'Ebmaj'), (b'Gbmaj', b'Gbmaj'), (b'Amin', b'Amin'), (b'Bmin', b'Bmin'), (b'Cmin', b'Cmin'), (b'Dmin', b'Dmin'), (b'Emin', b'Emin'), (b'Fmin', b'Fmin'), (b'Gmin', b'Gmin'), (b'Abmin', b'Abmin'), (b'Bbmin', b'Bbmin'), (b'Dbmin', b'Dbmin'), (b'Ebmin', b'Ebmin'), (b'Gbmin', b'Gbmin'), (b'Chromatic', b'Chromatic')], default=b'Select', max_length=20)),
                ('timesig_num', models.IntegerField(default=4)),
                ('timesig_denom', models.IntegerField(choices=[(1, b'1'), (2, b'2'), (4, b'4'), (8, b'8'), (16, b'16'), (32, b'32')], default=4)),
                ('audio_file', models.FileField(blank=True, null=True, upload_to=b'riff_audio/')),
                ('desc', models.TextField(blank=True, default=b'', max_length=200)),
                ('tab', models.TextField(default=b'G |----|\nD |----|\nA |----|\nE |----|\n', max_length=1000)),
                ('tags', models.CharField(default=b'', max_length=50)),
                ('document', models.FileField(blank=True, null=True, upload_to=b'riff_documents/')),
            ],
        ),
    ]
