# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-18 04:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='riff',
            name='riff_key',
            field=models.CharField(choices=[(b'A', b'A'), (b'B', b'B'), (b'C', b'C'), (b'D', b'D'), (b'E', b'E'), (b'F', b'F'), (b'G', b'G'), (b'Ab', b'Ab'), (b'Bb', b'Bb'), (b'Db', b'Db'), (b'Eb', b'Eb'), (b'Gb', b'Gb')], default=b'A', max_length=2),
        ),
    ]
