# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-21 03:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0002_auto_20171114_2112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='riff',
            name='audio_file',
            field=models.FileField(blank=True, null=True, upload_to='riff_audio/', verbose_name='Audio File'),
        ),
        migrations.AlterField(
            model_name='riff',
            name='desc',
            field=models.TextField(blank=True, default='', max_length=200, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='riff',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='riff_documents/', verbose_name='Documentation'),
        ),
        migrations.AlterField(
            model_name='riff',
            name='priv_vis',
            field=models.BooleanField(default=True, verbose_name='Private'),
        ),
        migrations.AlterField(
            model_name='riff',
            name='riff_key',
            field=models.CharField(choices=[('', 'Select'), ('Amaj', 'Amaj'), ('Bmaj', 'Bmaj'), ('Cmaj', 'Cmaj'), ('Dmaj', 'Dmaj'), ('Emaj', 'Emaj'), ('Fmaj', 'Fmaj'), ('Gmaj', 'Gmaj'), ('Abmaj', 'Abmaj'), ('Bbmaj', 'Bbmaj'), ('Dbmaj', 'Dbmaj'), ('Ebmaj', 'Ebmaj'), ('Gbmaj', 'Gbmaj'), ('Amin', 'Amin'), ('Bmin', 'Bmin'), ('Cmin', 'Cmin'), ('Dmin', 'Dmin'), ('Emin', 'Emin'), ('Fmin', 'Fmin'), ('Gmin', 'Gmin'), ('Abmin', 'Abmin'), ('Bbmin', 'Bbmin'), ('Dbmin', 'Dbmin'), ('Ebmin', 'Ebmin'), ('Gbmin', 'Gbmin'), ('Chromatic', 'Chromatic')], default='Select', max_length=20, verbose_name='Key'),
        ),
        migrations.AlterField(
            model_name='riff',
            name='tab',
            field=models.TextField(default='G |----|\nD |----|\nA |----|\nE |----|\n', max_length=1000, verbose_name='Tablature'),
        ),
        migrations.AlterField(
            model_name='riff',
            name='timesig_denom',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (4, '4'), (8, '8'), (16, '16'), (32, '32')], default=4, verbose_name='Time Signature Denominator'),
        ),
        migrations.AlterField(
            model_name='riff',
            name='timesig_num',
            field=models.IntegerField(default=4, verbose_name='Time Signature Numerator'),
        ),
    ]
