# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-18 04:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0002_riff_riff_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='riff',
            name='timesig_denom',
            field=models.IntegerField(choices=[(1, b'1'), (2, b'2'), (4, b'4'), (8, b'8'), (16, b'16'), (32, b'32')], default=4),
        ),
        migrations.AddField(
            model_name='riff',
            name='timesig_num',
            field=models.IntegerField(default=4),
        ),
    ]
