# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-26 02:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0003_auto_20171120_1903'),
    ]

    operations = [
        migrations.AlterField(
            model_name='riff',
            name='tags',
            field=models.TextField(default='', max_length=50),
        ),
    ]
