# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-25 04:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0004_auto_20171018_2119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='riff',
            name='riff_key',
            field=models.CharField(choices=[('', 'Select'), ('Amaj', 'Amaj'), ('Bmaj', 'Bmaj'), ('Cmaj', 'Cmaj'), ('Dmaj', 'Dmaj'), ('Emaj', 'Emaj'), ('Fmaj', 'Fmaj'), ('Gmaj', 'Gmaj'), ('Abmaj', 'Abmaj'), ('Bbmaj', 'Bbmaj'), ('Dbmaj', 'Dbmaj'), ('Ebmaj', 'Ebmaj'), ('Gbmaj', 'Gbmaj'), ('Amin', 'Amin'), ('Bmin', 'Bmin'), ('Cmin', 'Cmin'), ('Dmin', 'Dmin'), ('Emin', 'Emin'), ('Fmin', 'Fmin'), ('Gmin', 'Gmin'), ('Abmin', 'Abmin'), ('Bbmin', 'Bbmin'), ('Dbmin', 'Dbmin'), ('Ebmin', 'Ebmin'), ('Gbmin', 'Gbmin'), ('Chromatic', 'Chromatic')], default='Select', max_length=20),
        ),
    ]
