# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-02 00:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0005_auto_20171024_2105'),
    ]

    operations = [
        migrations.AddField(
            model_name='riff',
            name='audio_file',
            field=models.FileField(null=True, upload_to=b'riffs/'),
        ),
    ]
