# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-03 20:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0005_auto_20171128_2000'),
    ]

    operations = [
        migrations.AddField(
            model_name='riff',
            name='last_updated',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
