# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-02 00:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0005_auto_20171024_2105'),
    ]

    operations = [
        migrations.AddField(
            model_name='riff',
            name='desc',
            field=models.TextField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='riff',
            name='tab',
            field=models.TextField(default='G |----|\nD |----|\nA |----|\nE |----|\n', max_length=1000),
        ),
        migrations.AddField(
            model_name='riff',
            name='tags',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='riff',
            name='name',
            field=models.CharField(max_length=20),
        ),
    ]
