# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-03 22:43
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0006_riff_last_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='riff',
            name='timesig_num',
            field=models.IntegerField(default=4, validators=[django.core.validators.MaxValueValidator(99), django.core.validators.MinValueValidator(1)], verbose_name='Time Signature Numerator'),
        ),
    ]
