# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-02 00:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0006_riff_audio_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='riff',
            name='audio_file',
            field=models.FileField(blank=True, null=True, upload_to=b'riffs/'),
        ),
    ]
