# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-02 01:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0007_auto_20171102_0059'),
        ('collection', '0006_auto_20171101_1712'),
    ]

    operations = [
    ]
