# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-02 01:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0008_merge_20171102_0108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='riff',
            name='audio_file',
            field=models.FileField(blank=True, null=True, upload_to='riffs/'),
        ),
    ]
