# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-08 04:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0010_riff_pub_vis'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='riff',
            name='pub_vis',
        ),
        migrations.AddField(
            model_name='riff',
            name='priv_vis',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='riff',
            name='desc',
            field=models.TextField(blank=True, default='', max_length=200),
        ),
    ]
