# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-08 05:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0010_auto_20171108_0337'),
    ]

    operations = [
        migrations.AddField(
            model_name='riff',
            name='priv_vis',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='riff',
            name='desc',
            field=models.TextField(blank=True, default=b'', max_length=200),
        ),
    ]
