# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-08 04:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0010_auto_20171108_0337'),
        ('collection', '0011_auto_20171107_2000'),
    ]

    operations = [
    ]
