# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-08 04:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0012_merge_20171107_2010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='riff',
            name='audio_file',
            field=models.FileField(blank=True, null=True, upload_to='riff_audio/'),
        ),
        migrations.AlterField(
            model_name='riff',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='riff_documents/'),
        ),
        migrations.AlterField(
            model_name='riff',
            name='priv_vis',
            field=models.BooleanField(default=True),
        ),
    ]
